Clean up chat functions
googleinterns/step14-2020 pull request #78
Opened 2020-07-24 05:09 UTC by aokeke

Add some test cases for the chat functionality and make the tagRemovalRefs no longer global.

2020-07-24 07:23 UTC, aokeke commented on proj/src/main/webapp/test/chat.test.js
> +            // }
Considering if we should just never delete some test users so they can be reused. If you delete and recreate users too many times, firebase starts blocking your IP.

2020-07-24 17:14 UTC, nlumiere requested changes
Pretty sure there are gonna be some conflicts with current master

2020-07-24 20:05 UTC, leeannachen reviewed
lgtm

2020-07-24 20:05 UTC, leeannachen commented on proj/src/main/webapp/static/chat.html
> +                                            <div class="message-header justify-content-between">
added this line to my version and it fixed all the bugs 👍

2020-07-27 17:36 UTC, nlumiere approved these changes
I don't see why anything shouldn't work... Though lease test the more complicated things if you haven't already.

2020-07-27 17:36 UTC, nlumiere commented on proj/src/main/webapp/chat.js
>              }
This looks like it should work, but it's pretty convoluted still. I'm good with it as long as it's tested and confirmed to work.

2020-07-27 18:18 UTC, arringtonh approved these changes
lgtm!

2020-07-27 18:30 UTC, merged